
[2024-04-22 10:34:01.810440] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 24, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 19, in main
    print(1/0)
ZeroDivisionError: division by zero
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa

[2024-04-22 10:35:01.460779] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 24, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 19, in main
    print(1/0)
ZeroDivisionError: division by zero
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa
aaaaaaaaaaaaaa

[2024-04-22 10:36:01.675798] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:37:02.009670] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:38:01.243596] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:39:01.442367] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:40:01.097646] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:41:01.334052] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:42:01.796638] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:43:02.015011] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:44:01.288307] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:45:01.521030] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:46:01.720029] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:47:01.940259] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:48:01.265553] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:49:01.749828] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:50:01.928433] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:51:01.156419] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:52:01.478464] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:53:01.718653] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:54:01.971990] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:55:01.176251] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:56:01.428584] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 14, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 9, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:57:01.877463] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:58:01.094852] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 10:59:01.319091] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 11:00:01.516092] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 11:01:01.755071] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 11:02:01.046096] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 11:03:01.231526] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 11:04:01.463318] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 11:05:01.738410] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 11:06:01.997974] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero

[2024-04-22 11:07:01.355865] - Executing "gerar_erro"...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 13, in <module>
    main()
  File "/home/visie/hobbies/crontab-manager/src/scripts/gerar_erro.py", line 8, in main
    print(1/0)
ZeroDivisionError: division by zero
